# Generated by Django 4.0 on 2021-12-19 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('remaining_sessions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('session_count', models.IntegerField(default=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.client')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('duration_in_minutes', models.IntegerField(default=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.client')),
            ],
        ),
    ]
