# Generated by Django 4.0 on 2021-12-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='remaining_sessions',
        ),
    ]
