# Generated by Django 4.0 on 2021-12-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_client_remaining_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='sessions_at_purchase',
            field=models.IntegerField(default=4),
        ),
    ]
